development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: confucius_development
  pool: 5
  timeout: 5000
  username: confucius
  password:

test:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: confucius_test
  pool: 5
  timeout: 5000
  username: confucius
  password:
